### ISSUE TITLE
is it possible to get tables access policy(users/service account/ groups)

### ISSUE THREAD

**Issue by Opperessor** [googleapis/python-bigquery-datapolicies#31]
just wanted to know if this python package can get all the users of a table including groups/service account who has access to it (tables access policy) ?

**Comment by parthea** [comment]
You can use  [list_data_policies](https://cloud.google.com/python/docs/reference/bigquerydatapolicy/latest/google.cloud.bigquery.datapolicies_v1.services.data_policy_service.DataPolicyServiceClient#google_cloud_bigquery_datapolicies_v1_services_data_policy_service_DataPolicyServiceClient_list_data_policies) using the following sample code to list all data polices in a project, where `parent` should be in the form `projects/{project_number}/locations/{location_id}` as described in the linked documentation:
```
from google.cloud.bigquery import datapolicies_v1

def sample_list_data_policies():
    # Create a client
    client = datapolicies_v1.DataPolicyServiceClient()

    # Initialize request argument(s)
    request = datapolicies_v1.ListDataPoliciesRequest(
        parent="parent_value",
    )

    # Make the request
    page_result = client.list_data_policies(request=request)

    # Handle the response
    for response in page_result:
        print(response)
```

Then you can use [get_iam_policy](https://cloud.google.com/python/docs/reference/bigquerydatapolicy/latest/google.cloud.bigquery.datapolicies_v1.services.data_policy_service.DataPolicyServiceClient#google_cloud_bigquery_datapolicies_v1_services_data_policy_service_DataPolicyServiceClient_get_iam_policy) to get the corresponding IAM policy for any DataPolicy, where the `resource` field should be the name of the [DataPolicy](https://cloud.google.com/python/docs/reference/bigquerydatapolicy/latest/google.cloud.bigquery.datapolicies_v1.types.DataPolicy) in the format `projects/{project_number}/locations/{location_id}/dataPolicies/{data_policy_id}`. 

Use the following sample code to get the IAM policy for a given DataPolicy:

```
from google.cloud.bigquery import datapolicies_v1
from google.iam.v1 import iam_policy_pb2  # type: ignore

def sample_get_iam_policy():
    # Create a client
    client = datapolicies_v1.DataPolicyServiceClient()

    # Initialize request argument(s)
    request = iam_policy_pb2.GetIamPolicyRequest(
        resource="resource_value",
    )

    # Make the request
    response = client.get_iam_policy(request=request)

    # Handle the response
    print(response)
```

I'm going to close this issue but please open a new issue if you have additional questions, feature requests or issues.
